added streams
hotgluexyz/tap-restaurant365 pull request #10
Opened 2024-01-17 18:06 UTC by Jojo970

Locations
 Employee
 JobTitle
 LaborDetail
 POS Employee
 SalesEmployee
 SalesDetail
 SalesPayment
 EntityDeleted
AP Credit Memo
Bank Expense
Stock Count
TransactionDetails

The above streams were added

2024-01-17 20:06 UTC, hsyyid requested changes

2024-01-17 20:06 UTC, hsyyid commented on tap_restaurant365/streams.py
> +    def get_url_params(
Why is this `get_url_params` and `get_next_page_token` copied repeatedly? we don't want code duplication

2024-01-17 21:53 UTC, Jojo970 commented on tap_restaurant365/streams.py
> +    def get_url_params(
Fixed

2024-01-18 17:15 UTC, hsyyid approved these changes

2024-01-18 17:15 UTC, merged